---
- name: Llave para PPA NodeJS
  apt_key:
    url: "https://deb.nodesource.com/gpgkey/nodesource.gpg.key"
    state: present
  become: yes

- name: PPA de NodeJS
  apt_repository:
    repo: deb https://deb.nodesource.com/node_6.x xenial main
    state: present
    filename: nodejs6
  become: yes

## Crear usuario NodeRed
- user: 
    name: nodered
    state: present
    system: no             
    createhome: yes        
    home: /home/nodered  

- name: Instalar nodejs
  apt: name=nodejs state=present
  become: yes

- name: Instalar NodeRed
  command: npm install -g --unsafe-perm node-red
  become: yes


- name: Crear Servicio NodeRed
  template: src=nodered.service dest=/etc/systemd/system/nodered.service

- name: reload systemd unit configuration
  command: systemctl daemon-reload


- name: Service NodeRed Enabled
  command: systemctl enable nodered.service
  become: yes


- name: Run NodeRed
  command: systemctl start nodered.service
  become: yes
  async: 45
  poll: 0
